// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu1drJ4qEKGpKMqZ2tn44okZR7cp35ZWw',
    appId: '1:251643207614:web:ca65b32bec02fa7fef23ef',
    messagingSenderId: '251643207614',
    projectId: 'doinikcakri',
    authDomain: 'doinikcakri.firebaseapp.com',
    storageBucket: 'doinikcakri.appspot.com',
    measurementId: 'G-GJ9NSWPZ6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzP5Ux91p2P0cjA3dR5hqEuvCe-aqit4',
    appId: '1:251643207614:android:c8b81c11a8c9af37ef23ef',
    messagingSenderId: '251643207614',
    projectId: 'doinikcakri',
    storageBucket: 'doinikcakri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71Lq_MXu2h2M3xQCnHSikNxxgZ3mBSsU',
    appId: '1:251643207614:ios:eba80ae0fd4045b4ef23ef',
    messagingSenderId: '251643207614',
    projectId: 'doinikcakri',
    storageBucket: 'doinikcakri.appspot.com',
    iosBundleId: 'com.job.doinikcakri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71Lq_MXu2h2M3xQCnHSikNxxgZ3mBSsU',
    appId: '1:251643207614:ios:eba80ae0fd4045b4ef23ef',
    messagingSenderId: '251643207614',
    projectId: 'doinikcakri',
    storageBucket: 'doinikcakri.appspot.com',
    iosBundleId: 'com.job.doinikcakri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu1drJ4qEKGpKMqZ2tn44okZR7cp35ZWw',
    appId: '1:251643207614:web:e114b21c6c5eec10ef23ef',
    messagingSenderId: '251643207614',
    projectId: 'doinikcakri',
    authDomain: 'doinikcakri.firebaseapp.com',
    storageBucket: 'doinikcakri.appspot.com',
    measurementId: 'G-TPQBFKSCN3',
  );
}
